package model;
// Generated 20-jun-2019 0:35:13 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Jugador generated by hbm2java
 */
public class Jugador  implements java.io.Serializable {


     private BigDecimal codigo;
     private String nombre;
     private String apellido;
     private String dui;

    public Jugador() {
    }

	
    public Jugador(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Jugador(BigDecimal codigo, String nombre, String apellido, String dui) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.apellido = apellido;
       this.dui = dui;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }




}


